Mодуль 3
js-tasks-ru/jsbasic-20221114_marina210 pull request #3
Opened 2022-12-05 15:43 UTC by Bamavi

2022-12-05 15:44 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-12-06 13:41 UTC, SinimaWath requested changes

2022-12-06 13:41 UTC, SinimaWath commented on 3-module/3-task/index.js
> +   }
Сложное решение, получилось, давай использовать методы массива:

Решение нужно попытаться уложить в 3 этапа
```
return str
   .split('-')
   .map((value, index) => ....) // тут надо сделать первый символ заглавным
   .join('')
```

2022-12-07 14:34 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-12-07 17:20 UTC, SinimaWath approved these changes

2022-12-07 17:20 UTC, merged